# Generated by Django 4.2.3 on 2023-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="following",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
