# Generated by Django 4.2.3 on 2023-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_following_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="following",
            name="mute",
            field=models.BooleanField(default=False),
        ),
    ]
