# Generated by Django 4.2.3 on 2023-07-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(default="New Notification", max_length=255),
        ),
    ]
