# Generated by Django 4.2.3 on 2023-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="mute",
            field=models.BooleanField(default=False),
        ),
    ]
