# Generated by Django 4.2.3 on 2023-07-29 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_notification_mute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created",)},
        ),
    ]
